<b>Tout d'abord il faut importer les librairies dont j'ai besoin pour prepocessing mes données <b>
<hr />

!pip install langdetect

In [116]:
import pandas as pd
import numpy as np
#Pour tokenisation et normalisation les corpus
import nltk
from nltk import *
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.tag.stanford import StanfordPOSTagger
from nltk import StanfordTagger
#Detecteur lanquage du text
from langdetect import detect
import time
import re
import string
import spacy
from spacy.lang.fr.stop_words import STOP_WORDS as fr_stop
from spacy.lang.en.stop_words import STOP_WORDS as en_stop
#Pour clustering les annonces
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

<b>Les Fonctionnes:<b>
<hr />

In [117]:
#1# "normalisationCorpus" est une fonctionne qui va ajouter la colonne 'phrase_token' qui contiendra le nom
#de metier et sa description en miniscule
#et trois colonnes vides 'phrases_cible', 'resume' et 'category' afin d'être utiliser dans le preprocessing

def normalisationCorpus(df):
    donnees = df
    corpus = ""
    donnees['phrase_token']=""
    for index, row in donnees.iterrows():
        donnees.loc[index,'entreprise'] = str(donnees.loc[index,'entreprise'])
        corpus = "titre " +donnees.loc[index,'metier'].lower() +". "+ "sommaire "+donnees.loc[index,'sommaire'].lower()+". "+ donnees.loc[index,'description'].lower() +"."
        donnees.loc[index,'phrase_token'] = sent_tokenize(corpus)
    donnees['phrases_cible']=""
    donnees['resume']=""
    donnees['category'] = ""
    return donnees

#2# langueDetecte est une fonctionne qui va detecter les annonces anglais et puis il les supprimes

def langueDetecte(df):
    #count = 0
    donnees = df
    for index, row in donnees.iterrows():
        lang = detect(donnees.loc[index,'description'])
        if lang == "en" :
            #count+=1
            donnees = donnees.drop(index)
    #print(count)
    return donnees

#3# "nettoayage" est une fonctionne afin de chercher quelques mots ciblés qui peuvent contenir les compétences

def nettoayage(df):
    donnees = df
    collect=""
    corpus = ""
    mots_cible=["expérience","profil","compétence","mission","mont","capacité","dispos","maitris","titre","sommaire"]
    for index, row in donnees.iterrows():
        corpus = donnees.loc[index,"phrase_token"]
        for phrase in corpus:
            if any(mot in phrase for mot in mots_cible):
                collect = collect +" " + phrase + " \n"
        #Ici pour je supprime de mon corpus tous les mots cible dans la variable mots_cible
        mots = collect.split()

        motsResultat  = [mot for mot in mots if mot.lower() not in mots_cible]
        resultat = ' '.join(motsResultat)
        donnees.loc[index,"phrases_cible"] = resultat
        collect = ""
        
    return donnees

#4# "stopMots" est une fonctionne qui va supprimmer les mots frequants comme (de,le,la,je,avec,...)
#dans le corpus pour qu'il soit plus propre pour l'étape de machine learning

def stopMots(df):
    corpus = ""
    sans=""
    monList = ['de','et','vous','des','à','la','en','les','sur','vos','le','leur','',"l'",'pour','avec','êtes','votre','chaque','est','sont','du','ils','leurs','que','par','un','une','revenus','première',]
    stopWords = list(stopwords.words('french'))+list(fr_stop) + list(en_stop)+monList
    donnees = df
    transl_table = dict( [ (ord(x), ord(y)) for x,y in zip( u"‘'’´“”–-",  u"''''\"\"--") ] )
    for index, row in donnees.iterrows():
        corpus = donnees.loc[index,"phrases_cible"].replace("d'"," ").replace("l'"," ")
        corpus = corpus.translate(transl_table)
        corpus = corpus.translate(str.maketrans('','',string.punctuation)).replace("’"," ").replace("'"," ")
        tokens = word_tokenize(corpus, language='french')
        for token in tokens:
            if token not in stopWords :
                sans = sans + " " + token+ " "
        donnees.loc[index,"resume"] = sans
        sans = ""
    return donnees

#IMPORTATION LES DONNEES
<hr />

In [118]:
mainDataFrame = pd.read_csv("annonces.csv")

#PREMIERE VUE DE MES DONNEES
<hr />

In [119]:
mainDataFrame.head(5)

,id,motcle,metier,entreprise,location,datedannoce,lien,sommaire,description
0,1,data analyste,Stage Chef de Projet,Animaux Vie et Santé,Wasquehal (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Animaux Vie et Santé est une petite filiale de...,"Offre : Stage de 6 mois, à partir de janvier 2..."
1,2,data analyste,Data Analyst Etudes Marketing H/F,Leroy Merlin,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,En s’appuyant sur des organisations disruptive...,Qui sommes-nous ? \n Face à un marché de plus ...
2,3,data analyste,Data Analyst / Engineer H/F,AMD Consulting,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Contexte de la missionL'équipe Performance Eco...,"AMD consulting, est un acteur reconnu dans le ..."
3,4,data analyste,Un(e) Data Analyst F/H (IT),CELAD,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,"Dans le domaine de la Grande Distribution, nou...","Dans le domaine de la Grande Distribution, nou..."
4,5,data analyste,Data Analyst,Strathom,Villeneuve-d'Ascq (59),il y a 18 jours,https://fr.indeed.com/rc/clk?jk=6dc1f78291259d...,"Data analyst, DataViz, Informatique, Modélisat...","data analyst, DataViz, Informatique, Modélisat..."

In [120]:
mainDataFrame.tail(5)

,id,motcle,metier,entreprise,location,datedannoce,lien,sommaire,description
1883,1884,js,Développement front-end/back-end de statistiqu...,Worldline,Seclin (59),Il y a plus de 30 jours,https://fr.indeed.com/rc/clk?jk=6a934db76c855c...,Worldline [Euronext: WLN] is the European lead...,About Worldline \n Worldline [Euronext: WLN] i...
1884,1885,js,Développeur Fullstack Confirmé (H/F),Ineat Conseil,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/rc/clk?jk=4fa90d04e4e5dc...,Découvrez une organisation qui vous donne les ...,Contrat : CDI \n \nDisponibilité : ASAP \n \...
1885,1886,js,Architecte Technique (F/H) / Freelance,IZYFREE,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/rc/clk?jk=3afd8bc077cf18...,Votre mission consistera à: - Accompagner le d...,Votre mission consistera à: - Accompagner le ...
1886,1887,js,Développeur Drupal 8 Fullstack / Freelance,GROUPE HN,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Au sein d’une équipe pluridisciplinaire vous p...,Au sein d’une équipe pluridisciplinaire vous p...
1887,1888,js,Ingénieur Etude et Développement Front-End Jav...,Nextoo,Roubaix (59),Il y a plus de 30 jours,https://fr.indeed.com/rc/clk?jk=13c2c5f55dccfa...,Chez nos clients ou au sein de notre Centre De...,Chez nos clients ou au sein de notre Centre De...

In [121]:
mainDataFrame.shape

(1888, 9)

<b>Mon dataset contien 1888 LIGNES ET 9 COLONNES</b>

In [123]:
(mainDataFrame.loc[:,"description"].isnull() == False).count()

1888

<b>Et il n'y a pas de champs vide dans la colonne description</b>

<br />
<b> NETTOYAGE : </b>
<hr />

In [124]:
#dans mon data set Il y avait 71 annonces en anglais qu'il faut être supprimé
#Supprimer les annonce en Anglais
mainDataFrame = langueDetecte(mainDataFrame)

#je veux mettre id comme l'index de mon dataframe
mainDataFrame = mainDataFrame.set_index('id')

#Supprimer les dedoublons
mainDataFrame = mainDataFrame.drop_duplicates(subset='lien', keep="first")

#Normalisation à l'aide de la fonction "normalisationCorpus"
mainDataFrame = normalisationCorpus(mainDataFrame)

#Nettoayage les corpus à l'aide de la fonction "nettoayage"
mainDataFrame = nettoayage(mainDataFrame)

#Supprimer les mots frequants à l'aide de la fonction "stopMots"
mainDataFrame = stopMots(mainDataFrame)

71

In [125]:
mainDataFrame.head(5)

,motcle,metier,entreprise,location,datedannoce,lien,sommaire,description,phrase_token,phrases_cible,resume,category
id,,,,,,,,,,,,
1,data analyste,Stage Chef de Projet,Animaux Vie et Santé,Wasquehal (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Animaux Vie et Santé est une petite filiale de...,"Offre : Stage de 6 mois, à partir de janvier 2...","[titre stage chef de projet., sommaire animaux...",stage chef de projet. animaux vie et santé est...,stage chef projet animaux vie santé pet...,
2,data analyste,Data Analyst Etudes Marketing H/F,Leroy Merlin,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,En s’appuyant sur des organisations disruptive...,Qui sommes-nous ? \n Face à un marché de plus ...,"[titre data analyst etudes marketing h/f., som...",data analyst etudes marketing h/f. en s’appuya...,data analyst etudes marketing hf sappuya...,
3,data analyste,Data Analyst / Engineer H/F,AMD Consulting,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Contexte de la missionL'équipe Performance Eco...,"AMD consulting, est un acteur reconnu dans le ...","[titre data analyst / engineer h/f., sommaire ...",data analyst / engineer h/f. contexte de la mi...,data analyst engineer hf contexte missio...,
4,data analyste,Un(e) Data Analyst F/H (IT),CELAD,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,"Dans le domaine de la Grande Distribution, nou...","Dans le domaine de la Grande Distribution, nou...","[titre un(e) data analyst f/h (it)., sommaire ...",un(e) data analyst f/h (it). dans le domaine d...,data analyst fh domaine grande distribut...,
5,data analyste,Data Analyst,Strathom,Villeneuve-d'Ascq (59),il y a 18 jours,https://fr.indeed.com/rc/clk?jk=6dc1f78291259d...,"Data analyst, DataViz, Informatique, Modélisat...","data analyst, DataViz, Informatique, Modélisat...","[titre data analyst., sommaire data analyst, d...","data analyst. data analyst, dataviz, informati...",data analyst data analyst dataviz inform...,

<b>TESTING</b>
<hr />

<b>TF-IDF</b>
<hr />
<p>TF-IDF signifie "Term Frequency - Inverse Document Frequency".<br />
C'est une technique pour quantifier un mot dans les documents,
nous calculons généralement un poids à chaque mot qui signifie
l'importance du mot dans le document et le corpus.     <br />        
Cette méthode est une technique largement utilisée dans la    
    recherche d'informations et l'exploration de textes.</p>
<hr />

In [126]:
# CRÉER UN VARIABLE TTfidfVectorizer 
tfv = TfidfVectorizer(ngram_range = (1,1))

#TRANSFORMEZ LA COLONNE RESUME AU FORMAT VECTEUR DE POIDS
vec_text = tfv.fit_transform(mainDataFrame.loc[:,"resume"])

#Retourner une liste des mots fréquants.
words = tfv.get_feature_names()

In [127]:
# CONFIGURATION LE CLUSTERING AVEC KMEAN
kmeans = KMeans(n_clusters = 20, n_init = 17, n_jobs = -1, tol = 0.01, max_iter = 200)
# FIT LES DONNÉES AVEC LA VECTEUR vec_text
kmeans.fit(vec_text)
# Transformer les nombres aux mots correspondants
#common_words = kmeans.cluster_centers_.argsort()[:,-1:-11:-1]
#for num, centroid in enumerate(common_words):
#    print(str(num) + ' : ' + ', '.join(words[word] for word in centroid))

/home/negar/anaconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:938: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"

0 : développeur, js, react, stack, conseil, nodejs, freelance, node, recherche, consistera
1 : informatique, technicien, support, utilisateurs, informatiques, incidents, windows, réseaux, systèmes, gestion
2 : web, développement, développeur, net, projets, applications, compétences, projet, missions, technique
3 : data, données, analyst, big, engineer, accompagner, compétences, analyse, retail, business
4 : espacefreelance, directs, indépendants, consultants, lun, réseau, recherche, régie, hf, pourvoir
5 : téléphonie, description, progresser, activités, 3500, plusieurs, assurées, informatique, répartis, bagage
6 : sécurité, réseaux, réseau, systèmes, ingénieur, informatique, compétences, système, infrastructures, dune
7 : communication, startup, mode, valeur, possèdes, mois, faire, responsable, optimises, vs
8 : prime, vacances, ticket, salle, prévoyance, de, restaurant, mutuelle, analyste, participation
9 : technicienne, cloud, expérimentée, capacités, installer, infrastructures, souhaité, offrons, épanouir, démontrer
10 : marketing, projet, chef, clients, hf, poste, formation, ecommerce, client, gestion
11 : horaires, travail, ans, flexibles, 00000, souhaité, télétravail, temps, cdi, emploi
12 : devras, compétences, mettre, bon, qualités, désirées, relever, cse, sii, fungenieur
13 : java, développement, devops, spring, angular, compétences, technologies, techniques, tests, nodejs
14 : gestion, annexes, maintenance, informatique, parc, serveurs, 00000, dau, linux, chef
15 : stage, mois, seo, communication, marketing, durée, sociaux, référencement, rédacteur, contenus
16 : cloud, devops, azure, compétences, aws, google, terraform, système, gcp, public
17 : consultant, etl, problématiques, data, relationnelles, urbaniste, leader, talend, team, équipe
18 : concevoir, langages, code, dépendances, matérielle, kanban, configurer, linfrastructure, java, interroger
19 : celery, restauration, incident, rapide, redis, haut, cas, disponibilité, kafka, principale

In [128]:
#Associer chaque annonce au son cluster correspondant
mainDataFrame['category'] = kmeans.labels_

In [129]:
#Voir le resultat
mainDataFrame.head(5)

,motcle,metier,entreprise,location,datedannoce,lien,sommaire,description,phrase_token,phrases_cible,resume,category
id,,,,,,,,,,,,
1,data analyste,Stage Chef de Projet,Animaux Vie et Santé,Wasquehal (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Animaux Vie et Santé est une petite filiale de...,"Offre : Stage de 6 mois, à partir de janvier 2...","[titre stage chef de projet., sommaire animaux...",stage chef de projet. animaux vie et santé est...,stage chef projet animaux vie santé pet...,15
2,data analyste,Data Analyst Etudes Marketing H/F,Leroy Merlin,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,En s’appuyant sur des organisations disruptive...,Qui sommes-nous ? \n Face à un marché de plus ...,"[titre data analyst etudes marketing h/f., som...",data analyst etudes marketing h/f. en s’appuya...,data analyst etudes marketing hf sappuya...,3
3,data analyste,Data Analyst / Engineer H/F,AMD Consulting,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,Contexte de la missionL'équipe Performance Eco...,"AMD consulting, est un acteur reconnu dans le ...","[titre data analyst / engineer h/f., sommaire ...",data analyst / engineer h/f. contexte de la mi...,data analyst engineer hf contexte missio...,3
4,data analyste,Un(e) Data Analyst F/H (IT),CELAD,Lille (59),Il y a plus de 30 jours,https://fr.indeed.com/pagead/clk?mo=r&ad=-6NYl...,"Dans le domaine de la Grande Distribution, nou...","Dans le domaine de la Grande Distribution, nou...","[titre un(e) data analyst f/h (it)., sommaire ...",un(e) data analyst f/h (it). dans le domaine d...,data analyst fh domaine grande distribut...,3
5,data analyste,Data Analyst,Strathom,Villeneuve-d'Ascq (59),il y a 18 jours,https://fr.indeed.com/rc/clk?jk=6dc1f78291259d...,"Data analyst, DataViz, Informatique, Modélisat...","data analyst, DataViz, Informatique, Modélisat...","[titre data analyst., sommaire data analyst, d...","data analyst. data analyst, dataviz, informati...",data analyst data analyst dataviz inform...,3

In [130]:
#Exporter les données traitées finales
mainDataFrame.to_csv('final.csv',header=True)